// Code generated by protoc-gen-go.
// source: ping.proto
// DO NOT EDIT!

package ping

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// The request message containing the user's name.
type PingMsg struct {
	Val              *bool  `protobuf:"varint,1,opt,name=val" json:"val,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PingMsg) Reset()         { *m = PingMsg{} }
func (m *PingMsg) String() string { return proto.CompactTextString(m) }
func (*PingMsg) ProtoMessage()    {}

func (m *PingMsg) GetVal() bool {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return false
}

type PingResponse struct {
	Val              *bool  `protobuf:"varint,1,opt,name=val" json:"val,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}

func (m *PingResponse) GetVal() bool {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return false
}

func init() {
}
